"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Booking = { id:string; pickup:string; destination:string; customer_name:string; phone:string; travel_date:string; pickup_time:string|null; vehicle:string; fare_total:number; status:string; driver_name:string|null; driver_phone:string|null; admin_note:string|null };
const defaultProperties = `booking.fee=99\nvehicle.go.baseDayFare=1300\nvehicle.plus.baseDayFare=1600\nvehicle.xl.baseDayFare=2200\nvehicle.go.perKm=13\nvehicle.plus.perKm=15\nvehicle.xl.perKm=20\ndriver.dayAllowance=350\ndriver.overnightStay=800\ndistance.roadFactor=1.18\ndistance.minimumKm=20\ngst.percent=5\nairport.bookingFee=149\nairport.go.baseFare=1300\nairport.plus.baseFare=1600\nairport.xl.baseFare=2200\nairport.go.perKm=13\nairport.plus.perKm=15\nairport.xl.perKm=20\nairport.waiting.freeMinutes=30\nairport.waiting.perHour=200`;

export default function AdminPage() {
  const [token, setToken] = useState(() => typeof window === "undefined" ? "" : sessionStorage.getItem("vayora-admin") || ""); const [bookings, setBookings] = useState<Booking[]>([]); const [properties, setProperties] = useState(defaultProperties); const [tab, setTab] = useState<"requests"|"calendar"|"fares">("requests"); const [message, setMessage] = useState("");
  useEffect(() => { if (token) void load(token); /* initial authenticated load */ }, [token]);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/admin/login", { method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")}) }); const result=await response.json(); if(response.ok){setToken(result.token);sessionStorage.setItem("vayora-admin",result.token);load(result.token);}else setMessage(result.error); }
  async function load(auth=token) { const headers={authorization:`Bearer ${auth}`}; const [b,f]=await Promise.all([fetch("/api/admin/bookings",{headers}),fetch("/api/admin/fares",{headers})]); const bj=await b.json(); const fj=await f.json(); if(b.ok)setBookings(bj); else setMessage(bj.error); if(fj.properties)setProperties(fj.properties); }
  async function updateBooking(id:string, form:HTMLFormElement) { const data=new FormData(form); const response=await fetch("/api/admin/bookings",{method:"PATCH",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({id,status:data.get("status"),driverName:data.get("driverName"),driverPhone:data.get("driverPhone"),adminNote:data.get("adminNote")})}); const result=await response.json();setMessage(result.error||"Booking updated.");if(response.ok)load(); }
  async function saveFares(){const response=await fetch("/api/admin/fares",{method:"PUT",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({properties})});const result=await response.json();setMessage(result.message||result.error);}
  const calendar=useMemo(()=>bookings.filter(b=>b.status==="approved").sort((a,b)=>String(a.travel_date).localeCompare(String(b.travel_date))),[bookings]);
  if(!token)return <main className="portal-page"><section className="admin-login"><Link className="brand" href="/"><span className="brand-mark">V</span><span>Vayora</span></Link><p className="eyebrow">Private administration</p><h1>Admin sign in</h1><form className="lookup-card" onSubmit={login}><label><span>Admin email</span><input name="email" type="email" defaultValue="natul0636@gmail.com" required/></label><label><span>Password</span><input name="password" type="password" required/></label><button className="primary-button">Sign in securely</button></form><p className="booking-status">{message}</p></section></main>;
  return <main className="admin-page"><header className="admin-header"><Link className="brand" href="/"><span className="brand-mark">V</span><span>Vayora Admin</span></Link><button onClick={()=>{sessionStorage.removeItem("vayora-admin");setToken("");}}>Sign out</button></header><div className="admin-tabs">{(["requests","calendar","fares"] as const).map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t[0].toUpperCase()+t.slice(1)}{t==="requests"&&<span>{bookings.filter(b=>b.status==="pending").length}</span>}</button>)}</div><p className="booking-status admin-message">{message}</p>
    {tab==="requests"&&<section className="admin-grid">{bookings.map(b=><form className="admin-booking-card" key={b.id} onSubmit={e=>{e.preventDefault();updateBooking(b.id,e.currentTarget)}}><div className="record-heading"><div><p>{b.id}</p><h3>{b.pickup} → {b.destination}</h3></div><span className={`status-pill status-${b.status}`}>{String(b.status).replaceAll("_"," ")}</span></div><p>{b.customer_name} · {b.phone} · {b.travel_date} {b.pickup_time}</p><p>{b.vehicle} · ₹{Number(b.fare_total).toLocaleString("en-IN")}</p><div className="admin-fields"><label><span>Status</span><select name="status" defaultValue={b.status}><option>pending</option><option>approved</option><option>rejected</option><option>completed</option></select></label><label><span>Driver name</span><input name="driverName" defaultValue={b.driver_name||""}/></label><label><span>Driver phone</span><input name="driverPhone" defaultValue={b.driver_phone||""}/></label><label className="full-field"><span>Admin note</span><textarea name="adminNote" defaultValue={b.admin_note||""}/></label></div><button className="primary-button">Save decision</button></form>)}</section>}
    {tab==="calendar"&&<section className="calendar-list"><h2>Approved journey calendar</h2>{calendar.length?calendar.map(b=><article key={b.id}><time>{new Date(`${b.travel_date}T00:00:00`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</time><div><h3>{b.pickup} → {b.destination}</h3><p>{b.pickup_time} · {b.customer_name} · {b.vehicle}</p></div></article>):<p>No approved bookings yet.</p>}</section>}
    {tab==="fares"&&<section className="fare-editor"><div><p className="eyebrow">Live configuration</p><h2>Fare properties</h2><p>Edit every fare in one place. Saving creates a live database override; the property file remains the safe default.</p></div><textarea value={properties} onChange={e=>setProperties(e.target.value)} spellCheck={false}/><button className="primary-button" onClick={saveFares}>Save and publish fares</button></section>}
  </main>;
}
